{
  dice {
    rollDice(numDice: 3, numSides: 6)
  }
  user(name: "Matt") {
    age
    name
  }
  versions(nameLike: "search") {
    desc
    version
    tags(x: 5) {
      parentDesc
      x
    }
  }
}
