type QueryDice {
  rollDice(numDice: Int!, numSides: Int): [Int]
}

type User {
  name: String
  age: Int
}

type Tags {
  parentDesc: String
  x: Int
}

type Version {
  desc: String
  version: String
  tags(x: Int): [Tags]
}

type QueryRoot {
  dice: QueryDice
  user(name: String): User
  versions(nameLike: String): [Version]
}

schema {
  query: QueryRoot
}
