type QueryDice {
  rollDice(numDice: Int!, numSides: Int): [Int]
}

type User {
  name: String
  age: Int
}

type Version {
  desc: String
  version: String
}

type QueryRoot {
  dice: QueryDice
  user(name: String): User
  versions: [Version]
}

schema {
  query: QueryRoot
}
